name: Deploy to Minikube using GitHub Actions

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and deploy to Minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Ensure the latest version is used

      - name: Setup Node.js 20  # Explicitly set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify Node.js version  # Verify the Node.js version
        run: node -v

      - name: Setup Minikube
        uses: medyagh/setup-minikube@master  # Ensure the correct version is used
        with:
          minikube-version: 'latest'

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Set up Docker environment
        run: eval $(minikube docker-env)

      - name: Verify Minikube status
        run: minikube status

      - name: Build Docker image
        run: |
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo "verifying images:"
          docker images

      - name: Deploy to Minikube
        run: kubectl apply -f k8s-node-app.yaml

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
