name: Deploy to Minikube using GitHub Actions

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and deploy to Minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to the latest version

      - name: Setup Minikube
        uses: medyagh/setup-minikube@master  # Revert to using the master branch
        with:
          minikube-version: 'latest'

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Build Docker image
        run: |
          export DOCKER_TLS_VERIFY="1"
          export DOCKER_HOST="tcp://127.0.0.1:60952"
          export DOCKER_CERT_PATH="/mnt/c/Users/Asus/.minikube/certs"
          export MINIKUBE_ACTIVE_DOCKERD="minikube"
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo "verifying images:"
          docker images

      - name: Deploy to Minikube
        run: kubectl apply -f k8s-node-app.yaml

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
